name: Link Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linkcheck:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          format: "markdown"
          args: ". --verbose"
